### ISSUE TITLE
refactor to state form

### ISSUE THREAD

**Issue by cheekujodhpur** [cheekujodhpur/projectlama#2]
To be able to easily integrate into a networked multiplayer, AI or other interfaces, we'll need the following refactor. We have the working game logic sans the TODO that a lone player cannot draw.

- The game takes as input the current game state ( what is on discard pile, which player's turn it is, _extrainfo )
- The game outputs either the next game state OR outputs what extra information it requires to calculate the next game state and from which player
- In the latter case, a handler function gathers the extra information from the appropriate source and the callback would calculate the next game state.

Said in other words, we need to decouple the user prompts from the game logic because 
1. The prompts serve to different users on a network
2. In case of an AI, the prompts don't serve to anyone.

**Comment by anujshetty** [comment]
Agreed, as mentioned in the 2nd bullet, the logic to calculate what the options the player has would be common to both AI and human, then we would pass the options to AI/human. For the first we would ideally have the option to plug in any different heuristic/algorithm (might need historical data of the round if it isn't already accessible/passed to it, like who played what); and for the second like you've mentioned we'd use user prompts.

**Comment by cheekujodhpur** [comment]
I think the 'game state calculator' can also write to a "history" stack. The sequence of states is the only information required...with an arguable definition of what exactly a state holds, but we can modify it after this refactor.

**Comment by anujshetty** [comment]
Yeah, although we want the only the public information, so storing the whole state with everyone's cards might not be necessary, just what move each player made (and what card played if any). Again this is probably not required now and can probably be added down the line.
