### ISSUE TITLE
Choice to return 1 or 10

### ISSUE THREAD

**Issue by anujshetty** [cheekujodhpur/projectlama#3]
https://github.com/cheekujodhpur/projectlama/blob/e826525d5d8932eb98f4a818e3d80d78dc6c8fb6/game/players.py#L29

Is this needed? I can't really think of a reason why someone wouldn't pick 10. However I guess it's possible in >2 players there might be some dynamics, whereinyou might not want to have too huge an advantage over the others? This would only be if there's a lot of potential for people to attack other players, although since we're not allowing communication between players, atleast they wouldn't be able to collude.

**Comment by cheekujodhpur** [comment]
Exactly why the use of term "Ideally"... can't think of a situation where 1
is better than 10 so no hurry to implement but good to note down.

sent from a handheld device. pardon typos and lack of brevity
